//Adding person with missing values:
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "testi-title2",
    "author": "author_test",
    "url": "1234.1234/testi",
    "likes": 5
}